"   __     __        ______        __       __
"  |  \   |  \      |      \      |  \     /  \
"  | $$   | $$       \$$$$$$      | $$\   /  $$
"  | $$   | $$        | $$        | $$$\ /  $$$
"   \$$\ /  $$        | $$        | $$$$\  $$$$
"    \$$\  $$         | $$        | $$\$$ $$ $$
"     \$$ $$         _| $$_       | $$ \$$$| $$
"      \$$$         |   $$ \      | $$  \$ | $$
"       \$           \$$$$$$       \$$      \$$
"
"

" ---- Basic Settings ----------------------------------------------------------

set shell=/usr/bin/zsh                          " set default shell
set noswapfile                                  " no swap files
syntax enable                                   " enable syntax
filetype plugin indent on
set mouse=a                                     " enable mouse
set number relativenumber                       "line numbers
set history=1000                                " command history
set signcolumn=yes numberwidth=6                "signcolumn and available width
set updatetime=300                              " delay for plugin trigger
set linebreak                                   " text wrap wont break words
set textwidth=80                                "line length
set title                                       " window title current file
set spell                                       " spell check
set nocompatible                                " no vi compatibility
set smartcase ignorecase incsearch              " searching and highlighting
set foldmethod=indent foldlevel=2 foldcolumn=2  " code folding
set foldlevelstart=99 foldopen+=jump            " auto fold open/close
set clipboard=unnamedplus                       " clipboard register
set tabstop=8 softtabstop=0                     " tab settings
set expandtab shiftwidth=2 smarttab
set breakindent                                 " smart wrapping indentation
set breakindentopt=shift:2,min:40,sbr
set showbreak=>>                                " shows line break
set showcmd                                     " key strokes in command line
set splitbelow splitright                       " new windows split right/bottom
set wildmenu wildmode=longest:full,full         " command autocompletion
set timeoutlen=1000 ttimeoutlen=1000            " timeout for keybind presses
set autowrite                                   " auto save
set confirm                                     " prompt to save not error
set undofile                                    " persistent undo
set listchars=tab:>-                            " no endline chars
set hidden                                      " hide buffers instead of close
set termguicolors                               " better colors


" ---- Plugins -----------------------------------------------------------------

call plug#begin('~/.config/nvim/plugged')
  " Status bar {
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
  " }
  " File tree {
    Plug 'ms-jpq/chadtree', {'branch': 'chad', 'do': 'python3 -m chadtree deps'}
  " }
  " Commenting {
    Plug 'preservim/nerdcommenter'
  " }
  " Tags {
    Plug 'preservim/tagbar', { 'on': 'TagbarToggle' }
  " }
  " LSP {
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'pechorin/any-jump.vim'                " jump to definition/reference
    Plug 'folke/trouble.nvim'                   " better loc list
    Plug 'ms-jpq/coq_nvim', {'branch': 'coq'}
    Plug 'ms-jpq/coq.artifacts', {'branch': 'artifacts'}
  " }
  " fuzzy finders {
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim'        " search files within vim
    Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
    Plug 'ctrlpvim/ctrlp.vim'
  " }
  " Focus helpers {
    Plug 'junegunn/goyo.vim'
    Plug 'junegunn/limelight.vim'
  " }
  " Sessions {
    Plug 'xolox/vim-misc'
    Plug 'xolox/vim-session'                    " Save sessions
  " }
  " Lang Plugins {
    Plug 'lervag/vimtex'
  " }
  " Git {
    Plug 'tpope/vim-fugitive'                   " Git inside vim
    Plug 'airblade/vim-gitgutter'               " show changes in signcolumn
  " }
  " Visuals/syntax {
    Plug 'thaerkh/vim-indentguides'
    Plug 'flazz/vim-colorschemes'
    Plug 'luochen1990/rainbow'                  " bracket coloring
    Plug 'sheerun/vim-polyglot'                 " Syntax highlighting
    Plug 'blueyed/vim-diminactive'
    Plug 'stevearc/dressing.nvim'               " prettier boxes like on rename
  " }
  " Quality of Life {
    Plug 'jiangmiao/auto-pairs'                 " autoclose deimiters
    Plug 'alvan/vim-closetag'                   " autoclose html esq tags
    Plug 'tpope/vim-surround'                   " edit tags/delimiters in pairs
    Plug 'mhinz/vim-startify'                   " start screen
    Plug 'ryanoasis/vim-devicons'               " fancy icons
    Plug 'kyazdani42/nvim-web-devicons'
    Plug 'ConradIrwin/vim-bracketed-paste'      " autoset paste mode
    Plug 'antoinemadec/FixCursorHold.nvim'
    Plug 'sudormrfbin/cheatsheet.nvim'          " fuzzy cheatsheet
    Plug 'axieax/urlview.nvim'
    Plug 'easymotion/vim-easymotion'            " better movement
    Plug 'psliwka/vim-smoothie'
    " run code snippets
    Plug 'michaelb/sniprun', {'do': 'bash install.sh'}
  " }
  " Multiline editing {
    " multicursor
    Plug 'mg979/vim-visual-multi', {'branch': 'master'}
    Plug 'matze/vim-move'                       " move blocks
    Plug 'tommcdo/vim-lion'                     " line up text
  " }
  " Tmux {
    Plug 'christoomey/vim-tmux-navigator'
    Plug 'tmux-plugins/vim-tmux'
  " }
  " snippets {
   Plug 'SirVer/ultisnips'
   Plug 'honza/vim-snippets'
  " }
  " markdown {
    " view markdown in file
    Plug 'ellisonleao/glow.nvim', {'branch': 'main'}
    Plug 'vimwiki/vimwiki'
    Plug 'gabrielelana/vim-markdown'            " syntax
  " }

  call plug#end()


" ---- Plugin Settings ---------------------------------------------------------

" airline {
  " display all buffers if one tab open
  let g:airline#extensions#tabline#enabled = 1
  " how file paths are shown
  let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
  let g:airline_powerline_fonts = 1             " powerline integration
  let g:airline_theme='bubblegum'               " status bar theme
  let g:airline#extensions#tagbar#enabled = 1
  let g:airline#extensions#tagbar#flags = 'f'
" }
" NerdComment {
  let g:NERDSpaceDelims = 1                     " add space after comment char
  let g:NERDCompactSexyComs = 1                 " short syntax in comment blocks
" }
" Vim-Session {
  let g:session_autosave = 'yes'                " auto save session periodically
" }
" Rainbow Brackets {
  let g:rainbow_active = 1                      " rainbow brackets
" }
" Indent Guides {
  let g:indentguides_spacechar = '|'            " indent guide chars
  let g:indentguides_tabchar = '|'
" }
" Limelight {
  let g:limelight_conceal_ctermfg = 'gray'      " Color dimming
  let g:limelight_conceal_guifg = 'DarkGray'
" }
" Supertab {
  let g:SuperTabDefaultCompletionType = "<c-n>"
" }
" ctrlp {
  " ignore files in git and gitignore
  let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
" }
" vim wiki {
  " set markdown syntax and filepath
  let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]
" }
" vim markdown {
  let g:markdown_mapping_switch_status = '<Leader>s'
" }


" ---- Extra Settings ----------------------------------------------------------

" change cursor shape
let &t_SI = "\<Esc>[6 q"                        " insert mode, vertical bar
let &t_SR = "\<Esc>[4 q"                        " replace mode, underscore
let &t_EI = "\<Esc>[2 q"                        " normal mode, block

" Auto Formatting
command! -nargs=0 Format :call CocActionAsync('format')
" highlight symbol on press
autocmd CursorHold * silent call CocActionAsync('highlight')
" colorscheme
set background=dark
let g:gruvbox_number_column = 'bg1'
let g:gruvbox_contrast_dark = 'soft'
autocmd vimenter * ++nested colorscheme gruvbox

" Auto delete trailing whitespace, save cursor position
autocmd BufWritePre * let currPos = getpos(".")
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritePre * %s/\n\+\%$//e
autocmd BufWritePre *.[ch] %s/\%$/\r/e
autocmd BufWritePre * cal cursor(currPos[1], currPos[2])

" WSL yank support
if system('uname -r') =~ "microsoft"
  augroup Yank
    autocmd!
    autocmd TextYankPost * :call system('/mnt/c/windows/system32/clip.exe ',@")
    augroup END
  endif

" highlight lines longer than 100 then 120 chars
call matchadd('OverLength', '\(\%101v\|\%121v\)', 200)

" fixes lag of exiting insert/visual mode
if !has('gui_running')
  set ttimeoutlen=10
  augroup FastEscape
    autocmd!
    au InsertEnter * set timeoutlen=0
    au InsertLeave * set timeoutlen=1000
  augroup END
endif

" Override colors
augroup vimrc
  autocmd!
  " autocmd ColorScheme * highlight ColorColumn cterm=bold ctermfg=196
  "     \ ctermbg=None guifg=Aqua guibg=NONE
  autocmd ColorScheme * highlight clear Search
        \ | highlight Search ctermbg=None ctermfg=None guibg=Grey42
  autocmd ColorScheme * highlight CocHighlightText ctermbg=None ctermfg=None guibg=Grey35
augroup END

" remember fold
augroup remember_folds
  autocmd!
  autocmd BufWinLeave * silent! mkview
  autocmd BufWinEnter * silent! loadview
augroup END

" get rid of auto commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" add cursorline when not in insert mode
autocmd VimEnter * set cul
autocmd InsertLeave * set cul
autocmd InsertEnter * set nocul

" show function signatures
augroup mygroup
  autocmd!
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')Lq

augroup end

" limelight integration
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

" Change highlight group of active/inactive windows
hi ActiveWindow guibg=#17252c
hi InactiveWindow guibg=#0D1B22

augroup WindowManagement
  autocmd!
  autocmd WinEnter * call Handle_Win_Enter()
augroup END

" highlight text over 100 chars
augroup highlightText
  autocmd!
  autocmd ColorScheme * highlight OverLength ctermbg=darkgrey guibg=Grey30
  autocmd ColorScheme * match OverLength /\%101v.*/
augroup END

augroup COQ
  autocmd!
  autocmd VimEnter * COQnow -s
augroup END


" ---- Keybindings -------------------------------------------------------------

let mapleader = " "                               " Leader Character to Space
" COC {
  " errors
  nnoremap <silent> cd <cmd>call coc#rpc#request('fillDiagnostics',
        \ [bufnr('%')])<CR><cmd>Trouble loclist<CR>
  nnoremap cl :silent! TroubleClose<CR>
  nnoremap <silent> gn :lnext<CR>
  nnoremap <silent> gp :lprev<CR>
  " Coc navigation
  nnoremap <silent> cy <Plug>(coc-type-definition)
  nnoremap <silent> ci <Plug>(coc-implementation)
  nnoremap <silent> cr <Plug>(coc-references)
  " better documentation and scroll through
  nnoremap <silent> K :call <SID>show_documentation()<CR>
  if has('nvim-0.4.0') || has('patch-8.2.0750')
    nnoremap <silent><nowait><expr> <A-j> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
    nnoremap <silent><nowait><expr> <A-k> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
    inoremap <silent><nowait><expr> <A-j> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
    inoremap <silent><nowait><expr> <A-k> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
    vnoremap <silent><nowait><expr> <A-j> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
    vnoremap <silent><nowait><expr> <A-k> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  endif
  " misc
  nnoremap <leader>ac   <Plug>(coc-codeaction-selected)w
  nnoremap <leader>qf  <Plug>(coc-fix-current)
  nnoremap <leader>rn <Plug>(coc-rename)
" }
" autocomplete {
let g:coq_settings = { "keymap.recommended": v:false }
  inoremap <expr> <CR>            pumvisible() ? "\<C-y>" : "\<CR>"
  inoremap <silent><expr> <Esc>   pumvisible() ? "\<C-e><Esc>" : "\<Esc>"
  inoremap <silent><expr> <C-c>   pumvisible() ? "\<C-e><C-c>" : "\<C-c>"
  inoremap <silent><expr> <BS>    pumvisible() ? "\<C-e><BS><C-e>"  : "\<BS>"
  inoremap <silent><expr> <CR>    pumvisible() ? (complete_info().selected == -1 ? "\<C-e><CR>" : "\<C-y>") : "\<CR>"
  inoremap <silent><expr> <tab>   pumvisible() ? "\<Down>" : "\<Tab>"
  inoremap <silent><expr> <Esc>[z pumvisible() ? "\<Up>" : "\<Esc>[z"
set completeopt=noinsert
" }
" Multiline {
  let g:VM_maps = {}
  let g:VM_maps["Add Cursor Down"] = '<Leader>.'
  let g:VM_maps["Add Cursor Up"] = '<Leader>,'
  let g:VM_maps["Undo"] = 'u'
  let g:VM_maps["Redo"] = '<C-r>'
" }
" Goyo {
  nnoremap <silent> gy :Goyo<CR>
  nnoremap <silent> gy! :Goyo!<CR>
" }

" Limelight {
  nnoremap <silent> lime :Limelight<CR>
  nnoremap <silent> !lime :Limelight!<CR>
" }
" CHADTree {
  nnoremap <silent> <Leader>nt :CHADopen<CR>
  nnoremap <silent> <Leader>ng :CHADopen --version-ctl<CR>
" }
" Vim Session {
  nnoremap <Leader>o :OpenSession<CR><cr>
  nnoremap <Leader>s :SaveSession<CR>
" }
" UltiSnips {
  let g:UltiSnipsExpandTrigger="<s-tab>"
  let g:UltiSnipsJumpForwardTrigger="<c-b>"
  let g:UltiSnipsJumpBackwardTrigger="<c-z>"
" }
" Tagbar {
  nnoremap <Leader>tt :TagbarToggle<CR>
" }
" Windows {
  " shift+key to switch windows
  nnoremap <S-h> <C-w>h
  nnoremap <S-j> <C-w>j
  nnoremap <S-k> <C-w>k
  nnoremap <S-l> <C-w>l
  " create new windows
  nnoremap <Leader>v <C-w>v
  nnoremap <Leader>h <C-w>s
" }
" Buffers {
  " change buffers
  nnoremap <Leader>bn :w \| bn<cr>
  nnoremap <Leader>bd :bd<cr>
  nnoremap <Leader>bp :w \| bp<cr>
" }
" Misc {
  " enter to get rid of highlights
  nnoremap <cr> :noh<CR><CR>
  " exit vim command mode
  tnoremap <Esc> <C-\><C-n>
" }
" Delimiter Tabs {
  " toggle hl search
  nnoremap / :set hlsearch<cr>/
  nnoremap i :set nohlsearch<cr>i
  " ctrl+d out of delimiters
  inoremap <c-d> <left><c-o>/["')>}\]]<cr><c-o>:noh<cr><right>
" }
" Visual Block Mode {
  command! Vb normal! <C-v>
  nnoremap <silent> vb :Vb<CR>
" }
" renaming {
  " local
  nnoremap gr gd[{V%::s/<C-R>///gc<left><left><left>
  " global
  nnoremap gR gD:%s/<C-R>///gc<left><left><left>
" }
" telescope {
  nnoremap ff :Telescope find_files<cr>
  nnoremap fg :Telescope live_grep<cr>
  nnoremap fb :Telescope buffers<cr>
  nnoremap fh :Telescope help_tags<cr>
" }
" gitgutter {
  nnoremap diff :GitGutterDiffOrig<cr>
  nmap <silent> <Leader>nh :call GitGutterNextHunkCycle()<CR>
  nmap <silent> <Leader>ph :call GitGutterPrevHunkCycle()<CR>
" }


" ---- Functions --------------------------------------------------------------

" manual show documentation
function! s:show_documentation()
  if (index(['vim', 'help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" git info in status line
  inoremap <silent><expr> <A-b> coc#refresh()
function! GitStatus()
  let [a,m,r] = GitGutterGetHunkSummary()
  return printf('+%d ~%d -%d', a, m, r)
endfunction
set statusline+=%{GitStatus()}

" cycle between hunks
function! GitGutterNextHunkCycle()
  let line = line('.')
  silent! GitGutterNextHunk
  if line('.') == line
    1
    GitGutterNextHunk
  endif
endfunction

function! GitGutterPrevHunkCycle()
  let line = line('.')
  silent! GitGutterPrevHunk
  if line('.') == line
    normal! G
    GitGutterPrevHunk
  endif
endfunction

function! Handle_Win_Enter()
  setlocal winhighlight=Normal:ActiveWindow,NormalNC:InactiveWindow
endfunction


" ---- NVIM Specifics ---------------------------------------------------------

if has("nvim")
lua << EOF
-- this is space for changing the settings of nvim only plugins
EOF
endif
