require("utils")

vim_opts({
	opt = {
    swapfile = false,
		number = true,
		signcolumn = "yes",
		numberwidth = 6,
		expandtab = true,
    tabstop = 2,
    softtabstop = 2,
		shiftwidth = 2,
		updatetime = 100,
		linebreak = true,
		textwidth = 100,
		smartcase = true,
		ignorecase = true,
		foldmethod = "indent",
		foldlevel = 2,
		foldcolumn = "2",
		foldlevelstart = 99,
		foldopen = "jump,block,hor,mark,percent,quickfix,search,tag,undo",
		foldenable = false,
		clipboard = "unnamedplus",
		breakindent = true,
		breakindentopt = "shift:2,min:40,sbr",
		showbreak = "=>>",
		scrolloff = 5,
		autowrite = true,
		confirm = true,
		autochdir = true,
		termguicolors = true,
    undofile = true,
	},
})

