local telescope = require("telescope")
telescope.load_extension("scope")
telescope.load_extension("aerial")
telescope.load_extension("notify")
telescope.load_extension("noice")
telescope.load_extension("projects")
